### ISSUE TITLE
Base16 theme

### ISSUE THREAD

**Issue by SevereOverfl0w** [AlessandroYorba/Alduin#3]
it would be really neat to try and become compatible with base16,

I put this together using a converter from iterm to xdefaults, then using the rgb values as the bases:

``` yml
scheme: "Alduin"
author: "Alessandro Yorba"
base00: "1c1c1c"
base01: "8b5f61"
base02: "d69f74"
base03: "747474"
base04: "8b373c"
base05: "5f3a3c"
base06: "87875f"
base07: "878787"
base08: "444444"
base09: "9e744d"
base0A: "c79a71"
base0B: "fed975"
base0C: "9e4c40"
base0D: "af0000"
base0E: "87afaf"
base0F: "ffffff"
```

It looks pretty neat, on my terminal, not so much in vim itself! :( I'm not sure what to look at next, however, it may be obvious to you what is up.

https://github.com/kowalskey/base16-builder/ This fork of the builder (if you use my above base16 scheme), will generate iterm files, & a number of others you may want to try out.

Hopefully you can reduce the load on yourself (maintaining multiple files), and bring support to a number of configs.
